Repository entando/entando-admin-console, pull requests merged in 2020-11, with the labels that each got.

#64 ENG-1468 remove app builder / admin console caption on header
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/header.jsp
Labels: approved, size/XS

#66 ENG-1478 Amend breadcrumbs
  src/main/java/org/entando/entando/apsadmin/api/package_en.properties
  src/main/java/org/entando/entando/apsadmin/api/package_it.properties
  src/main/webapp/WEB-INF/apsadmin/jsp/api/consumer-delete-confirm.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/api/consumer-entry.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/api/consumer-list.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/api/resource-detail.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/api/resource-list.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/api/service-delete-confirm.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/api/service-list.jsp
Labels: approved, size/S

#67 ENG-1478 Change breadcrumb icon
  src/main/webapp/resources/administration/patternfly/css/patternfly.css
  src/main/webapp/resources/administration/patternfly/css/patternfly.min.css
Labels: size/XS

#65 ENG-1467 matching labels breadcrumb/titles & menu
  src/main/java/com/agiletec/apsadmin/portal/package_en.properties
  src/main/java/com/agiletec/apsadmin/portal/package_it.properties
Labels: approved, size/XS

#68 ENG-1512: Added extra param "csp.header.extraConfig"
  src/test/config/conf/systemParams.properties
Labels: approved, size/XS

#69 ENG-1512: Update BOM and snapshot version
  pom.xml
  src/test/java/org/entando/entando/apsadmin/filebrowser/TestFileBrowserAction.java
Labels: approved, size/S
