Repository entando/entando-admin-console, pull requests merged in 2020-10, with the labels that each got.

#58 ENG-1348: Update pom xml for spring security oauth vulnerability
  pom.xml
Labels: approved, size/XS

#50 ENG-950 added bom import to pom
  jenkins-x.yml
  pom.xml
Labels: size/S

#57 ENG-1345 adapt adminconsole the the entanoengine vulnerability fixes
  pom.xml
  src/main/java/com/agiletec/apsadmin/category/helper/CategoryActionHelper.java
  src/main/java/com/agiletec/apsadmin/category/helper/ICategoryActionHelper.java
  src/main/java/com/agiletec/apsadmin/common/BaseCommonAction.java
  src/main/java/com/agiletec/apsadmin/portal/PageAction.java
  src/main/java/com/agiletec/apsadmin/portal/WidgetTypeAction.java
  src/main/java/com/agiletec/apsadmin/portal/helper/AbstractPageActionHelper.java
  src/main/java/com/agiletec/apsadmin/portal/helper/IPageActionHelper.java
  src/main/java/com/agiletec/apsadmin/system/ITreeNodeBaseActionHelper.java
  src/main/java/com/agiletec/apsadmin/system/TreeNodeBaseActionHelper.java
  src/main/java/com/agiletec/apsadmin/system/entity/type/CompositeAttributeConfigAction.java
  src/main/java/com/agiletec/apsadmin/tags/EntityInfoTag.java
  src/main/java/com/agiletec/apsadmin/tags/EntityTypeInfoTag.java
  src/main/java/com/agiletec/apsadmin/tags/util/AdminPagerTagHelper.java
  src/main/java/com/agiletec/apsadmin/user/group/GroupAction.java
  src/main/java/com/agiletec/apsadmin/user/group/helper/GroupActionHelper.java
  src/main/java/com/agiletec/apsadmin/user/group/helper/IGroupActionHelper.java
  src/main/java/com/agiletec/apsadmin/user/role/RoleAction.java
  src/main/java/org/entando/entando/aps/internalservlet/api/ApiResourceAction.java
  src/main/java/org/entando/entando/aps/internalservlet/api/ApiServiceAction.java
  src/main/java/org/entando/entando/apsadmin/api/AbstractApiAction.java
  src/main/java/org/entando/entando/apsadmin/api/ConsumerAction.java
  src/main/java/org/entando/entando/apsadmin/api/helper/SchemaGeneratorActionHelper.java
  src/main/java/org/entando/entando/apsadmin/common/UserAvatarAction.java
  src/main/java/org/entando/entando/apsadmin/common/currentuser/CurrentAvatarAction.java
  src/main/java/org/entando/entando/apsadmin/common/currentuser/CurrentUserProfileAction.java
  src/main/java/org/entando/entando/apsadmin/dataobject/helper/DataObjectActionHelper.java
  src/main/java/org/entando/entando/apsadmin/dataobject/helper/IDataObjectActionHelper.java
  src/main/java/org/entando/entando/apsadmin/dataobject/model/DataObjectModelAction.java
  src/main/java/org/entando/entando/apsadmin/portal/guifragment/helper/GuiFragmentActionHelper.java
  src/main/java/org/entando/entando/apsadmin/portal/guifragment/helper/IGuiFragmentActionHelper.java
  src/main/java/org/entando/entando/apsadmin/portal/model/PageModelAction.java
  src/main/java/org/entando/entando/apsadmin/portal/model/helper/IPageModelActionHelper.java
  src/main/java/org/entando/entando/apsadmin/portal/model/helper/PageModelActionHelper.java
  src/main/java/org/entando/entando/apsadmin/system/services/shortcut/IShortcutManager.java
  src/main/java/org/entando/entando/apsadmin/system/services/shortcut/ShortcutDefDOM.java
  src/main/java/org/entando/entando/apsadmin/system/services/shortcut/ShortcutLoader.java
  src/main/java/org/entando/entando/apsadmin/system/services/shortcut/ShortcutManager.java
  src/main/java/org/entando/entando/apsadmin/system/services/shortcut/UserShortcutConfigDOM.java
  src/main/java/org/entando/entando/apsadmin/system/services/shortcut/UserShortcutDAO.java
  src/main/java/org/entando/entando/apsadmin/tags/EntityTypesInfoTag.java
  src/main/java/org/entando/entando/apsadmin/user/UserAction.java
  src/main/java/org/entando/entando/apsadmin/user/UserAuthorizationAction.java
  src/main/java/org/entando/entando/apsadmin/user/UserProfileAction.java
  src/test/java/com/agiletec/apsadmin/portal/TestPageAction.java
  src/test/java/com/agiletec/apsadmin/portal/TestWidgetsViewerAction.java
  src/test/java/com/agiletec/apsadmin/user/group/TestGroupAction.java
  src/test/java/com/agiletec/apsadmin/user/role/TestRoleAction.java
  src/test/java/org/entando/entando/apsadmin/api/TestConsumerAction.java
  src/test/java/org/entando/entando/apsadmin/user/TestUserAction.java
  src/test/java/org/entando/entando/apsadmin/user/TestUserAuthorizationAction.java
Labels: approved, size/L

#56 ENG-1206: Introduced EMAIL attribute type
  src/main/java/org/entando/entando/apsadmin/common/currentuser/CurrentAvatarAction.java
  src/main/java/org/entando/entando/apsadmin/user/UserAuthorizationAction.java
  src/main/webapp/WEB-INF/apsadmin/jsp/entity/include/validation-rules-text.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/user/profile-entry.jsp
  src/test/java/com/agiletec/apsadmin/portal/TestPageAction.java
  src/test/java/org/entando/entando/apsadmin/user/TestUserAction.java
  src/test/java/org/entando/entando/apsadmin/user/TestUserAuthorizationAction.java
Labels: approved, size/M

#59 ENG-1244 readOnlyDefaultConfig added
  pom.xml
  src/main/java/com/agiletec/apsadmin/portal/WidgetTypeAction.java
  src/main/java/com/agiletec/apsadmin/portal/package_en.properties
  src/main/java/com/agiletec/apsadmin/portal/package_it.properties
  src/main/webapp/WEB-INF/apsadmin/jsp/portal/widget-entry.jsp
  src/test/java/org/entando/entando/apsadmin/user/TestUserProfileAction.java
  src/test/java/org/entando/entando/apsadmin/user/TestUserProfileFinderAction.java
Labels: approved, size/M

#60 ENG-1206: Added missing option
  src/main/webapp/WEB-INF/apsadmin/jsp/common/inc/profile-formFields.jsp
Labels: size/XS

#62 ENG-1206: Fix view user profile UI
  pom.xml
  src/main/webapp/WEB-INF/apsadmin/jsp/user/profile-view.jsp
Labels: approved, size/M

#61 ENG-1171: Fix random failures when saving contents
  pom.xml
  src/main/java/com/agiletec/apsadmin/system/entity/EntityActionHelper.java
  src/test/java/org/entando/entando/apsadmin/user/TestUserProfileFinderAction.java
Labels: approved, size/XS

#63 ENG-1244 readOnlyDefaultConfig refactoring and bom update
  pom.xml
  src/main/java/com/agiletec/apsadmin/portal/WidgetTypeAction.java
  src/main/java/com/agiletec/apsadmin/portal/package_en.properties
  src/main/java/com/agiletec/apsadmin/portal/package_it.properties
  src/main/webapp/WEB-INF/apsadmin/jsp/portal/widget-entry.jsp
Labels: approved, size/M
