Repository entando/entando-admin-console, pull requests merged in 2020-07, with the labels that each got.

#2 Eng 827 finalize pipelines
  pom.xml
  src/main/assembly/classes.xml
  src/main/webapp/resources/administration/js/entando.grid-generator.js
Labels: size/L

#3 ENG-811 hide data menu items
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/menu.jsp
Labels: size/M

#4 ENG-877: Add LICENSE file
  LICENSE
Labels: size/L

#6 ENG-787 menu with appBuilder integration added
  src/main/webapp/WEB-INF/apsadmin/jsp/common/layouts/default.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/menuAppBuilderIntegration.jsp
  src/main/webapp/WEB-INF/apsadmin/tiles.xml
Labels: size/XXL

#5 updating nomenclature according to new glossary
  src/main/java/com/agiletec/apsadmin/global-messages_en.properties
  src/main/java/com/agiletec/apsadmin/global-messages_it.properties
  src/main/java/com/agiletec/apsadmin/portal/package_en.properties
  src/main/java/com/agiletec/apsadmin/portal/package_it.properties
Labels: size/M

#8 ENG-771 connect AC with AB with links
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/header.jsp
Labels: size/S

#9 ENG-767 hide notification menu
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/header.jsp
Labels: size/M

#10 ENG-843 implement reading app title
  src/main/java/com/agiletec/apsadmin/global-messages_en.properties
  src/main/java/com/agiletec/apsadmin/global-messages_it.properties
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/header.jsp
Labels: size/S

#11 amend OWNERS and OWNER_ALIASES files
  OWNERS
  OWNERS_ALIASES
Labels: approved, size/S

#12 ENG-771 change licence to license
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/header.jsp
Labels: size/XS

#14 ENG-887 Fix overlapping vertical nav and chevron
  src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css
Labels: size/S

#15 ENG-764 Creating a common language selector
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/header.jsp
  src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css
Labels: approved, size/S

#13 ENG-879: update links in the integrated app-builder menu
  src/main/java/com/agiletec/apsadmin/global-messages_en.properties
  src/main/java/com/agiletec/apsadmin/global-messages_it.properties
  src/main/java/com/agiletec/apsadmin/portal/package_it.properties
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/menuAppBuilderIntegration.jsp
Labels: size/M

#17 ENG-900: fixing element positioning and labels
  src/main/java/com/agiletec/apsadmin/global-messages_en.properties
  src/main/java/com/agiletec/apsadmin/global-messages_it.properties
  src/main/java/com/agiletec/apsadmin/system/entity/package_en.properties
  src/main/java/com/agiletec/apsadmin/system/entity/package_it.properties
  src/main/java/org/entando/entando/apsadmin/user/package_en.properties
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/header.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/menuAppBuilderIntegration.jsp
  src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css
Labels: approved, size/M

#16 ENG-857 UX Quick Wins: modify button position and styles
  src/main/webapp/WEB-INF/apsadmin/jsp/common/template/dashboard.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/portal/guifragment/guiFragment-list.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/portal/model/pageModel-list.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/portal/pageTree.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/portal/widget-list.jsp
  src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css
Labels: approved, size/M

#18 amend OWNERS and OWNER_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: approved, size/S

#19 ENG-900 amended menu and labels
  src/main/java/com/agiletec/apsadmin/global-messages_en.properties
  src/main/java/com/agiletec/apsadmin/global-messages_it.properties
  src/main/java/com/agiletec/apsadmin/portal/package_it.properties
  src/main/java/com/agiletec/apsadmin/system/entity/package_it.properties
  src/main/java/org/entando/entando/apsadmin/portal/guifragment/package_it.properties
  src/main/java/org/entando/entando/apsadmin/portal/model/package_it.properties
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/header.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/menuAppBuilderIntegration.jsp
Labels: approved, size/M

#21 ENG-857 Change add button position in category and groups pages
  src/main/webapp/WEB-INF/apsadmin/jsp/category/categoryTree.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/user/group/groupFinding.jsp
Labels: approved, size/S

#20 ENG-907: making AC to watch changes on localStorage and update the locale accordingly
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/header.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/menuAppBuilderIntegration.jsp
Labels: approved, size/M

#22 ENG-930: removing bundle id field from widget edit/add screen
  src/main/webapp/WEB-INF/apsadmin/jsp/portal/widget-entry.jsp
Labels: approved, size/S

#23 Update package_en.properties
  src/main/java/com/agiletec/apsadmin/admin/lang/package_en.properties
Labels: approved, size/XS

#24 Update package_en.properties
  src/main/java/com/agiletec/apsadmin/admin/localestring/package_en.properties
Labels: approved, size/XS

#43 ENG-940 Fix alignment of language selection dropdown
  src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css
Labels: approved, size/XS

#44 ENG-942 Paul's ENG label fixes
  src/main/java/com/agiletec/apsadmin/admin/package_en.properties
  src/main/java/com/agiletec/apsadmin/common/package_en.properties
  src/main/java/com/agiletec/apsadmin/global-messages_en.properties
  src/main/java/com/agiletec/apsadmin/portal/package_en.properties
  src/main/java/com/agiletec/apsadmin/portal/specialwidget/navigator/package_en.properties
  src/main/java/com/agiletec/apsadmin/system/entity/package_en.properties
  src/main/java/com/agiletec/apsadmin/system/entity/type/package_en.properties
  src/main/java/com/agiletec/apsadmin/user/group/package_en.properties
  src/main/java/com/agiletec/apsadmin/user/role/package_en.properties
  src/main/java/org/entando/entando/apsadmin/admin/package_en.properties
  src/main/java/org/entando/entando/apsadmin/api/package_en.properties
  src/main/java/org/entando/entando/apsadmin/dataobject/model/package_en.properties
  src/main/java/org/entando/entando/apsadmin/filebrowser/package_en.properties
  src/main/java/org/entando/entando/apsadmin/global-messages_en.properties
  src/main/java/org/entando/entando/apsadmin/portal/guifragment/package_en.properties
  src/main/java/org/entando/entando/apsadmin/portal/model/package_en.properties
  src/main/java/org/entando/entando/apsadmin/user/package_en.properties
Labels: approved, size/L

#39 ENG-938: AdminConsole: amend menu (except CMS)
  src/main/java/com/agiletec/apsadmin/global-messages_en.properties
  src/main/java/com/agiletec/apsadmin/global-messages_it.properties
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/menuAppBuilderIntegration.jsp
Labels: approved, size/L

#45 ENG-938: fixing menu links and moving Category under Content section
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/menuAppBuilderIntegration.jsp
  src/main/webapp/resources/administration/css/pages/settingsPage.css
Labels: approved, size/M

#46 Eng 950 trim war
  pom.xml
  src/test/config/conf/systemParams.properties
Labels: approved, size/XS

#47 ENG-936 Amend CMS menu labels
  src/main/java/com/agiletec/apsadmin/global-messages_en.properties
  src/main/java/com/agiletec/apsadmin/global-messages_it.properties
Labels: approved, lgtm, size/S

#48 fixing Content label and icon
  src/main/java/com/agiletec/apsadmin/global-messages_it.properties
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/menuAppBuilderIntegration.jsp
Labels: approved, size/XS

#49 ENG-935: removing category as it was already being injected through plugin-jacms
  src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/menuAppBuilderIntegration.jsp
Labels: approved, size/S
