Repository entando/entando-admin-console, pull requests merged in 2021-07, with the labels that each got.

#76 ENG-2178: Remove Data Types and Data Models
  pom.xml
  src/main/java/org/entando/entando/apsadmin/dataobject/attribute/action/list/ListAttributeAction.java
  src/main/java/org/entando/entando/apsadmin/dataobject/helper/DataObjectActionHelper.java
  src/main/java/org/entando/entando/apsadmin/dataobject/helper/IDataObjectActionHelper.java
  src/main/java/org/entando/entando/apsadmin/dataobject/model/DataObjectModelAction-validation.xml
  src/main/java/org/entando/entando/apsadmin/dataobject/model/DataObjectModelAction.java
  src/main/java/org/entando/entando/apsadmin/dataobject/model/DataObjectModelFinderAction.java
  src/main/java/org/entando/entando/apsadmin/dataobject/model/dataObjectModel.xml
  src/main/java/org/entando/entando/apsadmin/dataobject/model/package_en.properties
  src/main/java/org/entando/entando/apsadmin/dataobject/model/package_it.properties
  src/main/java/org/entando/entando/apsadmin/dataobject/rs/model/DataObjectJO.java
  src/main/java/org/entando/entando/apsadmin/dataobject/rs/model/DataObjectsStatusResponse.java
  src/main/resources/spring/apsadmin/dataobject/dataobjectActionsConfig.xml
  src/main/resources/spring/apsadmin/dataobject/dataobjectModelActionsConfig.xml
  src/main/resources/struts.xml
  src/main/webapp/WEB-INF/apsadmin/jsp/datatype/ux/entryModel.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/datatype/ux/modelFinding.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/datatype/ux/modelReferences.jsp
  src/main/webapp/WEB-INF/apsadmin/jsp/datatype/ux/trashModel.jsp
  src/main/webapp/WEB-INF/apsadmin/tiles.xml
  src/test/java/com/agiletec/apsadmin/TestAdminConsoleLabelsProperties.java
  src/test/java/com/agiletec/apsadmin/category/TestCategoryAction.java
  src/test/java/com/agiletec/apsadmin/portal/TestPageAction.java
  src/test/java/com/agiletec/apsadmin/portal/TestPageTreeAction.java
  src/test/java/com/agiletec/apsadmin/user/group/TestGroupAction.java
  src/test/java/org/entando/entando/apsadmin/dataobject/model/TestDataObjectModelAction.java
  src/test/java/org/entando/entando/apsadmin/dataobject/model/TestDataObjectModelFinderAction.java
  src/test/java/org/entando/entando/apsadmin/portal/model/TestPageModelAction.java
Labels: approved, size/XXL

#87 ENG-2471 NewGen workflow
  .github/workflows/ga-publication.yml
  .github/workflows/post-merge.yml
  .github/workflows/pr.yml
  .github/workflows/publication.yml
Labels: approved, prepared, size/L

#89 ENG-2471 NewGen workflow v1.0.1
  .github/workflows/ga-publication.yml
  .github/workflows/post-merge.yml
  .github/workflows/pr.yml
  .github/workflows/publication.yml
Labels: prepared

#90 ENG-2471 updating develop branch with the missing master changes
  pom.xml
Labels: prepared

#88 ENG-2459 Adding snyk suppression file to suppress jdom false positive…
  .snyk
  pom.xml
Labels: prepared

#93 ENG-2459 update to the latest pom and bom
  pom.xml
Labels: prepared
