Repository entando/entando-admin-console, pull requests merged in 2021-04, with the labels that each got.

#77 ENG-2261: upgrade velocity version
  pom.xml
  src/main/java/com/agiletec/apsadmin/category/CategoryAction.java
  src/main/java/com/agiletec/apsadmin/portal/PageFinderAction.java
  src/main/java/com/agiletec/apsadmin/portal/PageTreeAction.java
  src/main/java/com/agiletec/apsadmin/portal/WidgetTypeAction.java
  src/main/java/com/agiletec/apsadmin/portal/specialwidget/navigator/NavigatorWidgetConfigAction.java
  src/main/java/org/entando/entando/aps/internalservlet/system/dispatcher/GuiFragmentResult.java
  src/main/java/org/entando/entando/apsadmin/dataobject/helper/DataObjectActionHelper.java
  src/main/java/org/entando/entando/apsadmin/portal/guifragment/GuiFragmentAction.java
  src/main/java/org/entando/entando/apsadmin/portal/guifragment/GuiFragmentFinderAction.java
  src/main/java/org/entando/entando/apsadmin/portal/model/PageModelAction.java
  src/main/java/org/entando/entando/apsadmin/user/UserAuthorizationAction.java
  src/main/java/org/entando/entando/apsadmin/user/UserProfileAction.java
Labels: approved, size/S

#78 ENG-2259 Fix the vulnarable dependencies (ppom 6.3.9)
  pom.xml
Labels: approved, size/XS

#79 ENG-2029: Migrate the AppEngine logging to logback
  pom.xml
  src/main/java/org/entando/entando/apsadmin/system/CustomTokenInterceptor.java
  src/main/java/org/entando/entando/apsadmin/system/tiles/EntandoStrutsTilesInitializer.java
  src/main/java/org/entando/entando/apsadmin/system/tiles/EntandoStrutsTilesListener.java
  src/main/java/org/entando/entando/apsadmin/system/validator/URLValidator.java
Labels: approved, size/M
